# Generated by Django 5.2.4 on 2025-12-04 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places_Lamp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_time', models.DateTimeField()),
                ('off_time', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LampSchedul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Places_Lamp.lamp')),
                ('user_schedul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Places_Lamp.userschedule')),
            ],
        ),
        migrations.DeleteModel(
            name='LampSchedule',
        ),
    ]
