# Generated by Django 5.2.4 on 2025-09-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places_Lamp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lamp',
            name='connection',
            field=models.BooleanField(default=False),
        ),
    ]
