# Generated by Django 5.2.4 on 2025-12-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places_Lamp', '0002_userschedule_lampschedul_delete_lampschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lamp',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('home', 'name')},
        ),
    ]
