# Generated by Django 5.2.4 on 2025-12-18 20:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places_Lamp', '0003_alter_lamp_name_alter_room_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='home',
            unique_together={('owner', 'name')},
        ),
    ]
