# Generated by Django 5.2.4 on 2025-11-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeuser',
            name='phone_number',
            field=models.CharField(default='None', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
