# Generated by Django 5.2.4 on 2025-08-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='is_service_provider',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
