openapi: 3.0.3
info:
  title: SmartLight
  version: 1.0.0
  description: Your project description
paths:
  /Account/login/:
    post:
      operationId: Account_login_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      tags:
      - Account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenObtainPair'
          description: ''
  /Account/register/:
    post:
      operationId: Account_register_create
      tags:
      - Account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserCreate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserCreate'
        required: true
      security:
      - jwtAuth: []
      - cookieAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserCreate'
          description: ''
  /Account/token/refresh/:
    post:
      operationId: Account_token_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - Account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
  /Profile/home/:
    get:
      operationId: Profile_home_list
      tags:
      - Profile
      security:
      - jwtAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HomeView'
          description: ''
    post:
      operationId: Profile_home_create
      tags:
      - Profile
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HomePost'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/HomePost'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/HomePost'
        required: true
      security:
      - jwtAuth: []
      - cookieAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HomePost'
          description: ''
  /Profile/home/{id}/:
    get:
      operationId: Profile_home_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this home.
        required: true
      tags:
      - Profile
      security:
      - jwtAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HomeView'
          description: ''
  /Profile/lamp/:
    get:
      operationId: Profile_lamp_list
      tags:
      - Profile
      security:
      - jwtAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LampView'
          description: ''
    post:
      operationId: Profile_lamp_create
      tags:
      - Profile
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LampPost'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/LampPost'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/LampPost'
        required: true
      security:
      - jwtAuth: []
      - cookieAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LampPost'
          description: ''
  /Profile/lamp/{id}/:
    get:
      operationId: Profile_lamp_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this lamp.
        required: true
      tags:
      - Profile
      security:
      - jwtAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LampView'
          description: ''
  /Profile/lamp_schedul/:
    get:
      operationId: Profile_lamp_schedul_list
      tags:
      - Profile
      security:
      - jwtAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LampViewSchedul'
          description: ''
    post:
      operationId: Profile_lamp_schedul_create
      tags:
      - Profile
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LampPostSchedul'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/LampPostSchedul'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/LampPostSchedul'
        required: true
      security:
      - jwtAuth: []
      - cookieAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LampPostSchedul'
          description: ''
  /Profile/lamp_schedul/{id}/:
    get:
      operationId: Profile_lamp_schedul_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this lamp schedul.
        required: true
      tags:
      - Profile
      security:
      - jwtAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LampViewSchedul'
          description: ''
  /Profile/room/:
    get:
      operationId: Profile_room_list
      tags:
      - Profile
      security:
      - jwtAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoomVIew'
          description: ''
    post:
      operationId: Profile_room_create
      tags:
      - Profile
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoomPost'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/RoomPost'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/RoomPost'
        required: true
      security:
      - jwtAuth: []
      - cookieAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoomPost'
          description: ''
  /Profile/room/{id}/:
    get:
      operationId: Profile_room_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this room.
        required: true
      tags:
      - Profile
      security:
      - jwtAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoomVIew'
          description: ''
components:
  schemas:
    HomePost:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 128
        shared_with_id:
          type: array
          items:
            type: integer
          writeOnly: true
      required:
      - id
      - name
    HomeView:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 128
        owner_username:
          type: string
          readOnly: true
        shared_with:
          type: array
          items:
            type: string
          readOnly: true
      required:
      - id
      - name
      - owner_username
      - shared_with
    LampPost:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
        status:
          type: boolean
        room:
          type: integer
          writeOnly: true
        shared_with_id:
          type: array
          items:
            type: integer
          writeOnly: true
      required:
      - id
      - name
      - room
    LampPostSchedul:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        user_schedul:
          type: integer
          writeOnly: true
        lamp:
          type: integer
          writeOnly: true
      required:
      - id
      - lamp
      - user_schedul
    LampView:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        room:
          type: string
          readOnly: true
        shared_with:
          type: array
          items:
            type: string
          readOnly: true
        name:
          type: string
          maxLength: 255
        status:
          type: boolean
        connection:
          type: boolean
        token:
          type: string
          format: uuid
          readOnly: true
      required:
      - id
      - name
      - room
      - shared_with
      - token
    LampViewSchedul:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        lamp:
          type: integer
        user_schedul:
          type: integer
      required:
      - id
      - lamp
      - user_schedul
    RoomPost:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
        home:
          type: integer
      required:
      - home
      - id
    RoomVIew:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
        home:
          type: string
      required:
      - home
      - id
    TokenObtainPair:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          readOnly: true
      required:
      - access
      - password
      - refresh
      - username
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
      required:
      - access
      - refresh
    UserCreate:
      type: object
      properties:
        username:
          type: string
          maxLength: 128
        email:
          type: string
          format: email
          maxLength: 128
        password:
          type: string
          maxLength: 128
        password2:
          type: string
          writeOnly: true
        phone_number:
          type: string
          maxLength: 20
      required:
      - email
      - password
      - password2
      - phone_number
      - username
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
